# Automatically run semantic checks, linters, and unit tests

name: Code Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-codes:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install uv and enable caching
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        version: "0.5.4"

    - name: Set up Python with uv
      run: uv python install

    - name: Install other dependencies
      run: |
        ./bin/install-dependencies.bash

    - name: Run check script
      run: |
        ./bin/check.bash

    - name: Clean up uv cache
      run: uv cache prune --ci
